sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - mysql
  - docker
before_install:
  - mysql --verbose -uroot < ./flyway-core/src/test/resources/migration/dbsupport/mysql/createDatabase.sql
  - echo "mariadb.url=jdbc:mariadb://localhost/flyway_maria_db" > ~/flyway-mediumtests.properties

install: ./mvnw install -DskipTests -P-CommercialDBTest,-CommandlinePlatformAssemblies

script: ./mvnw test -P-CommercialDBTest,-CommandlinePlatformAssemblies